import { TestData } from '@/types/test';
import { modularTestStorage } from '@/services/modularTestStorage';

export const getTestData = (testId: string): TestData => {
  // First check if it's an admin-created modular test
  const adminTest = modularTestStorage.getById(testId);
  if (adminTest) {
    return convertModularTestToTestData(adminTest);
  }

  // Fallback to static test data
  const testDataMap: { [key: string]: TestData } = {
    'digital-sat-practice': {
      id: 'digital-sat-practice',
      name: 'Digital SAT Practice Test',
      subject: 'Mixed',
      difficulty: 'Mixed',
      duration: 135,
      totalPoints: 300,
      instructions: 'Complete all 3 modules: Math Module 1 (10 questions), Reading Module (10 questions), Math Module 2 (10 questions). Take breaks between modules.',
      questions: [
        // Math Module 1 (Questions 1-10)
        {
          id: 'sat-m1-q1',
          type: 'MCQ',
          question: 'If 3x + 5 = 14, what is the value of x?',
          options: ['2', '3', '4', '5'],
          correctAnswer: '3',
          explanation: '3x + 5 = 14, so 3x = 9, therefore x = 3',
          points: 10,
          difficulty: 'Easy',
        },
        {
          id: 'sat-m1-q2',
          type: 'MCQ',
          question: 'What is 25% of 80?',
          options: ['15', '20', '25', '30'],
          correctAnswer: '20',
          explanation: '25% of 80 = 0.25 × 80 = 20',
          points: 10,
          difficulty: 'Easy',
        },
        {
          id: 'sat-m1-q3',
          type: 'Numeric',
          question: 'If f(x) = 2x + 1, what is f(5)?',
          correctAnswer: '11',
          explanation: 'f(5) = 2(5) + 1 = 10 + 1 = 11',
          points: 10,
          difficulty: 'Easy',
        },
        {
          id: 'sat-m1-q4',
          type: 'MCQ',
          question: 'Which of the following is equivalent to (x + 3)²?',
          options: ['x² + 6x + 9', 'x² + 3x + 9', 'x² + 9', 'x² + 6x + 3'],
          correctAnswer: 'x² + 6x + 9',
          explanation: '(x + 3)² = x² + 2(x)(3) + 3² = x² + 6x + 9',
          points: 10,
          difficulty: 'Medium',
        },
        {
          id: 'sat-m1-q5',
          type: 'MCQ',
          question: 'If y = 2x - 3 and x = 4, what is y?',
          options: ['3', '5', '7', '9'],
          correctAnswer: '5',
          explanation: 'y = 2(4) - 3 = 8 - 3 = 5',
          points: 10,
          difficulty: 'Easy',
        },
        {
          id: 'sat-m1-q6',
          type: 'Numeric',
          question: 'What is the slope of the line passing through points (2, 3) and (4, 7)?',
          correctAnswer: '2',
          explanation: 'Slope = (7-3)/(4-2) = 4/2 = 2',
          points: 10,
          difficulty: 'Medium',
        },
        {
          id: 'sat-m1-q7',
          type: 'MCQ',
          question: 'Which inequality represents x is greater than -2 and less than or equal to 5?',
          options: ['-2 < x ≤ 5', '-2 ≤ x < 5', '-2 > x ≥ 5', 'x > -2 or x ≤ 5'],
          correctAnswer: '-2 < x ≤ 5',
          explanation: 'x is greater than -2 (not equal) and less than or equal to 5',
          points: 10,
          difficulty: 'Medium',
        },
        {
          id: 'sat-m1-q8',
          type: 'MCQ',
          question: 'What is the value of √(64)?',
          options: ['6', '7', '8', '9'],
          correctAnswer: '8',
          explanation: '√64 = 8 because 8² = 64',
          points: 10,
          difficulty: 'Easy',
        },
        {
          id: 'sat-m1-q9',
          type: 'Numeric',
          question: 'If 2x - 7 = 15, what is x?',
          correctAnswer: '11',
          explanation: '2x - 7 = 15, so 2x = 22, therefore x = 11',
          points: 10,
          difficulty: 'Easy',
        },
        {
          id: 'sat-m1-q10',
          type: 'MCQ',
          question: 'What is the area of a circle with radius 3? (Use π ≈ 3.14)',
          options: ['18.84', '28.26', '37.68', '56.52'],
          correctAnswer: '28.26',
          explanation: 'Area = πr² = 3.14 × 3² = 3.14 × 9 = 28.26',
          points: 10,
          difficulty: 'Medium',
        },
        
        // Reading Module (Questions 11-20)
        {
          id: 'sat-r-q11',
          type: 'MCQ',
          question: 'Choose the word that best completes the sentence: "The scientist\'s hypothesis was _____ by the experimental results."',
          options: ['supported', 'rejected', 'ignored', 'questioned'],
          correctAnswer: 'supported',
          explanation: 'Context suggests the results confirmed the hypothesis',
          points: 10,
          difficulty: 'Medium',
        },
        {
          id: 'sat-r-q12',
          type: 'MCQ',
          question: 'Which sentence is grammatically correct?',
          options: [
            'Between you and I, this is difficult.',
            'Between you and me, this is difficult.',
            'Between yourself and I, this is difficult.',
            'Between yourself and myself, this is difficult.'
          ],
          correctAnswer: 'Between you and me, this is difficult.',
          explanation: 'After prepositions like "between," use object pronouns (me, not I)',
          points: 10,
          difficulty: 'Medium',
        },
        {
          id: 'sat-r-q13',
          type: 'MCQ',
          question: 'What is the main purpose of a thesis statement in an essay?',
          options: [
            'To introduce the topic',
            'To state the main argument',
            'To provide evidence',
            'To conclude the essay'
          ],
          correctAnswer: 'To state the main argument',
          explanation: 'A thesis statement presents the central claim or argument of the essay',
          points: 10,
          difficulty: 'Easy',
        },
        {
          id: 'sat-r-q14',
          type: 'MCQ',
          question: 'Which transition word best shows contrast?',
          options: ['Therefore', 'However', 'Furthermore', 'Similarly'],
          correctAnswer: 'However',
          explanation: 'However indicates a contrast or opposing idea',
          points: 10,
          difficulty: 'Easy',
        },
        {
          id: 'sat-r-q15',
          type: 'MCQ',
          question: 'In the sentence "The book, which was published in 1960, became a bestseller," the clause "which was published in 1960" is:',
          options: ['Essential', 'Non-essential', 'Independent', 'Compound'],
          correctAnswer: 'Non-essential',
          explanation: 'The clause is set off by commas and provides additional, non-essential information',
          points: 10,
          difficulty: 'Medium',
        },
        {
          id: 'sat-r-q16',
          type: 'MCQ',
          question: 'What does the prefix "pre-" mean?',
          options: ['After', 'Before', 'During', 'Without'],
          correctAnswer: 'Before',
          explanation: 'Pre- is a prefix meaning before (as in preview, prepare)',
          points: 10,
          difficulty: 'Easy',
        },
        {
          id: 'sat-r-q17',
          type: 'MCQ',
          question: 'Which punctuation mark is used to join two independent clauses?',
          options: ['Comma', 'Semicolon', 'Colon', 'Apostrophe'],
          correctAnswer: 'Semicolon',
          explanation: 'A semicolon can join two related independent clauses',
          points: 10,
          difficulty: 'Medium',
        },
        {
          id: 'sat-r-q18',
          type: 'MCQ',
          question: 'What is the comparative form of "good"?',
          options: ['Gooder', 'More good', 'Better', 'Best'],
          correctAnswer: 'Better',
          explanation: 'Better is the irregular comparative form of good',
          points: 10,
          difficulty: 'Easy',
        },
        {
          id: 'sat-r-q19',
          type: 'MCQ',
          question: 'In academic writing, which point of view is typically preferred?',
          options: ['First person', 'Second person', 'Third person', 'Mixed person'],
          correctAnswer: 'Third person',
          explanation: 'Academic writing typically uses third person for objectivity',
          points: 10,
          difficulty: 'Medium',
        },
        {
          id: 'sat-r-q20',
          type: 'Paragraph',
          question: 'Write a brief paragraph (3-4 sentences) explaining the importance of reading comprehension skills in academic success.',
          correctAnswer: '',
          explanation: 'Should discuss how reading comprehension affects learning across subjects',
          points: 10,
          difficulty: 'Hard',
        },
        
        // Math Module 2 (Questions 21-30) - Adaptive, harder questions
        {
          id: 'sat-m2-q21',
          type: 'MCQ',
          question: 'If log₂(x) = 5, what is the value of x?',
          options: ['10', '25', '32', '64'],
          correctAnswer: '32',
          explanation: 'log₂(x) = 5 means 2⁵ = x, so x = 32',
          points: 10,
          difficulty: 'Hard',
        },
        {
          id: 'sat-m2-q22',
          type: 'Numeric',
          question: 'What is the value of sin(30°)?',
          correctAnswer: '0.5',
          explanation: 'sin(30°) = 1/2 = 0.5',
          points: 10,
          difficulty: 'Hard',
        },
        {
          id: 'sat-m2-q23',
          type: 'MCQ',
          question: 'Which function represents exponential growth?',
          options: ['f(x) = 2x + 3', 'f(x) = x²', 'f(x) = 2ˣ', 'f(x) = 1/x'],
          correctAnswer: 'f(x) = 2ˣ',
          explanation: 'Exponential functions have the variable in the exponent',
          points: 10,
          difficulty: 'Hard',
        },
        {
          id: 'sat-m2-q24',
          type: 'MCQ',
          question: 'What is the vertex of the parabola y = x² - 4x + 3?',
          options: ['(2, -1)', '(2, 1)', '(-2, -1)', '(-2, 1)'],
          correctAnswer: '(2, -1)',
          explanation: 'Vertex form: x = -b/2a = 4/2 = 2, y = 4 - 8 + 3 = -1',
          points: 10,
          difficulty: 'Hard',
        },
        {
          id: 'sat-m2-q25',
          type: 'Numeric',
          question: 'If the discriminant of ax² + bx + c = 0 is 16, and a = 1, b = -4, what is c?',
          correctAnswer: '0',
          explanation: 'Discriminant = b² - 4ac = 16, so 16 - 4c = 16, therefore c = 0',
          points: 10,
          difficulty: 'Hard',
        },
        {
          id: 'sat-m2-q26',
          type: 'MCQ',
          question: 'What is the domain of f(x) = √(x - 3)?',
          options: ['x ≥ 3', 'x ≤ 3', 'x > 3', 'All real numbers'],
          correctAnswer: 'x ≥ 3',
          explanation: 'For square root to be defined, x - 3 ≥ 0, so x ≥ 3',
          points: 10,
          difficulty: 'Hard',
        },
        {
          id: 'sat-m2-q27',
          type: 'Numeric',
          question: 'What is the sum of the arithmetic sequence: 2, 5, 8, 11, 14?',
          correctAnswer: '40',
          explanation: '2 + 5 + 8 + 11 + 14 = 40',
          points: 10,
          difficulty: 'Medium',
        },
        {
          id: 'sat-m2-q28',
          type: 'MCQ',
          question: 'If matrix A = [2 3; 1 4], what is det(A)?',
          options: ['5', '7', '8', '11'],
          correctAnswer: '5',
          explanation: 'det(A) = (2)(4) - (3)(1) = 8 - 3 = 5',
          points: 10,
          difficulty: 'Hard',
        },
        {
          id: 'sat-m2-q29',
          type: 'MCQ',
          question: 'What is the period of the function f(x) = sin(2x)?',
          options: ['π/2', 'π', '2π', '4π'],
          correctAnswer: 'π',
          explanation: 'Period of sin(bx) is 2π/b, so 2π/2 = π',
          points: 10,
          difficulty: 'Hard',
        },
        {
          id: 'sat-m2-q30',
          type: 'Numeric',
          question: 'If lim(x→2) (x² - 4)/(x - 2) = L, what is L?',
          correctAnswer: '4',
          explanation: 'Factor: (x-2)(x+2)/(x-2) = x+2, limit as x→2 is 4',
          points: 10,
          difficulty: 'Hard',
        },
      ],
    },
    'free-module-1-2': {
      id: 'free-module-1-2',
      name: 'Complete Math Test - Modules 1 & 2',
      subject: 'Math',
      difficulty: 'Mixed',
      duration: 90,
      totalPoints: 200,
      instructions: 'Complete Module 1 (10 questions), take a 5-minute break, then complete Module 2 (10 questions).',
      questions: [
        // Module 1 Questions (10 questions)
        {
          id: 'q1-m1',
          type: 'MCQ',
          question: 'What is 2 + 3?',
          options: ['4', '5', '6', '7'],
          correctAnswer: '5',
          explanation: 'Basic addition: 2 + 3 = 5',
          points: 10,
          difficulty: 'Easy',
        },
        {
          id: 'q2-m1',
          type: 'MCQ',
          question: 'Solve: x + 5 = 12',
          options: ['5', '6', '7', '8'],
          correctAnswer: '7',
          explanation: 'x = 12 - 5 = 7',
          points: 10,
          difficulty: 'Easy',
        },
        {
          id: 'q3-m1',
          type: 'Numeric',
          question: 'Calculate 15% of 80',
          correctAnswer: '12',
          explanation: '15% of 80 = 0.15 × 80 = 12',
          points: 10,
          difficulty: 'Easy',
        },
        {
          id: 'q4-m1',
          type: 'MCQ',
          question: 'Which is a prime number?',
          options: ['4', '6', '11', '12'],
          correctAnswer: '11',
          explanation: '11 is prime - only divisible by 1 and itself',
          points: 10,
          difficulty: 'Medium',
        },
        {
          id: 'q5-m1',
          type: 'Numeric',
          question: 'Solve: 3x = 21',
          correctAnswer: '7',
          explanation: 'x = 21 ÷ 3 = 7',
          points: 10,
          difficulty: 'Easy',
        },
        {
          id: 'q6-m1',
          type: 'MCQ',
          question: 'What is 6²?',
          options: ['12', '24', '36', '42'],
          correctAnswer: '36',
          explanation: '6² = 6 × 6 = 36',
          points: 10,
          difficulty: 'Easy',
        },
        {
          id: 'q7-m1',
          type: 'Numeric',
          question: 'Find the mean of: 4, 6, 8, 10',
          correctAnswer: '7',
          explanation: 'Mean = (4 + 6 + 8 + 10) ÷ 4 = 28 ÷ 4 = 7',
          points: 10,
          difficulty: 'Medium',
        },
        {
          id: 'q8-m1',
          type: 'MCQ',
          question: 'Simplify: 2(x + 3)',
          options: ['2x + 3', '2x + 6', 'x + 6', '2x + 9'],
          correctAnswer: '2x + 6',
          explanation: '2(x + 3) = 2x + 6',
          points: 10,
          difficulty: 'Medium',
        },
        {
          id: 'q9-m1',
          type: 'Image',
          question: 'What is the area of this rectangle?',
          options: ['15 sq units', '20 sq units', '25 sq units', '30 sq units'],
          correctAnswer: '20 sq units',
          explanation: 'Area = length × width = 5 × 4 = 20 square units',
          points: 10,
          difficulty: 'Medium',
          imageUrl: '/placeholder.svg',
        },
        {
          id: 'q10-m1',
          type: 'Paragraph',
          question: 'Explain what a linear equation is and give an example.',
          correctAnswer: '',
          explanation: 'A linear equation is an equation where variables have a power of 1',
          points: 10,
          difficulty: 'Medium',
        },
        // Module 2 Questions (10 questions)
        {
          id: 'q11-m2',
          type: 'MCQ',
          question: 'What is the circumference formula for a circle?',
          options: ['πr²', '2πr', 'πd²', '2πd'],
          correctAnswer: '2πr',
          explanation: 'Circumference = 2πr where r is radius',
          points: 10,
          difficulty: 'Medium',
        },
        {
          id: 'q12-m2',
          type: 'Numeric',
          question: 'Find the area of a circle with radius 3 (use π = 3.14)',
          correctAnswer: '28.26',
          explanation: 'Area = πr² = 3.14 × 3² = 3.14 × 9 = 28.26',
          points: 10,
          difficulty: 'Medium',
        },
        {
          id: 'q13-m2',
          type: 'MCQ',
          question: 'In a right triangle, what is the relationship between sides?',
          options: ['a + b = c', 'a² + b² = c²', 'a × b = c', 'a² - b² = c²'],
          correctAnswer: 'a² + b² = c²',
          explanation: 'Pythagorean theorem: a² + b² = c²',
          points: 10,
          difficulty: 'Medium',
        },
        {
          id: 'q14-m2',
          type: 'Numeric',
          question: 'Find the perimeter of a square with side length 7',
          correctAnswer: '28',
          explanation: 'Perimeter = 4 × side = 4 × 7 = 28',
          points: 10,
          difficulty: 'Easy',
        },
        {
          id: 'q15-m2',
          type: 'MCQ',
          question: 'How many degrees are in a triangle?',
          options: ['90°', '180°', '270°', '360°'],
          correctAnswer: '180°',
          explanation: 'Sum of angles in any triangle is 180°',
          points: 10,
          difficulty: 'Easy',
        },
        {
          id: 'q16-m2',
          type: 'Image',
          question: 'What type of angle is shown?',
          options: ['Acute', 'Right', 'Obtuse', 'Straight'],
          correctAnswer: 'Right',
          explanation: 'A 90° angle is called a right angle',
          points: 10,
          difficulty: 'Easy',
          imageUrl: '/placeholder.svg',
        },
        {
          id: 'q17-m2',
          type: 'Numeric',
          question: 'Calculate the volume of a cube with side 4',
          correctAnswer: '64',
          explanation: 'Volume = side³ = 4³ = 64',
          points: 10,
          difficulty: 'Medium',
        },
        {
          id: 'q18-m2',
          type: 'MCQ',
          question: 'What is the slope of a horizontal line?',
          options: ['0', '1', 'undefined', 'infinity'],
          correctAnswer: '0',
          explanation: 'Horizontal lines have zero slope',
          points: 10,
          difficulty: 'Medium',
        },
        {
          id: 'q19-m2',
          type: 'Numeric',
          question: 'Find the diagonal of a rectangle with length 6 and width 8',
          correctAnswer: '10',
          explanation: 'Diagonal = √(6² + 8²) = √(36 + 64) = √100 = 10',
          points: 10,
          difficulty: 'Hard',
        },
        {
          id: 'q20-m2',
          type: 'Paragraph',
          question: 'Describe the properties of a parallelogram and explain how it differs from a rectangle.',
          correctAnswer: '',
          explanation: 'Parallelogram has opposite sides parallel and equal; rectangle is a special parallelogram with right angles',
          points: 10,
          difficulty: 'Hard',
        },
      ],
    },
  };

  return testDataMap[testId] || testDataMap['digital-sat-practice'];
};

// Convert ModularTest to TestData format
const convertModularTestToTestData = (modularTest: any): TestData => {
  // Flatten all questions from all modules
  const allQuestions = modularTest.modules.flatMap((module: any) => 
    module.questions.map((q: any) => ({
      id: q.id,
      type: q.type,
      question: q.question,
      options: q.options,
      correctAnswer: q.correctAnswer,
      explanation: q.explanation,
      points: q.points,
      imageUrl: q.imageUrl,
      difficulty: module.difficulty,
    }))
  );

  return {
    id: modularTest.id,
    name: modularTest.name,
    subject: modularTest.modules.length > 0 ? modularTest.modules[0].subject : 'Mixed',
    difficulty: 'Mixed', // Since modular tests can have mixed difficulties
    duration: modularTest.totalDuration,
    totalPoints: modularTest.totalScore,
    instructions: modularTest.description,
    questions: allQuestions,
    passage: modularTest.modules.find((m: any) => m.passage)?.passage,
  };
};
